#相關的空格不可以用tab來空！！
language: node_js
node_js:
- "6"
- "6.1"
- "5.11"
cache:
    directories:
        - node_modules
before_install:
    -npm install -g
    -npm install istanbul mocha coveralls --save-dev
script:
    -npm test 
    -npm run dev
    -npm run build
    -npm run checkdir
after_script:
    -npm run coverage
